#!/usr/bin/env ruby
#
# I18n tests in ruby.
#
# Robert Haines

require 'i18n'

I18n.load_path << Dir[File.expand_path('locales') + '/*.yml']

puts 'This will always be in English.'

locale = ((ENV['LC_ALL'] || ENV['LC_MESSAGES'] || ENV['LANG'])[0...2]).to_sym
I18n.locale =
  I18n.available_locales.include?(locale) ? locale : I18n.default_locale

puts "Locale: #{I18n.locale}"
puts I18n.t 'test'
